import { freshRuntime } from "./roster";
import type { Investigation, SweepEvent } from "./types";

function ev(partial: SweepEvent): SweepEvent {
  return partial;
}

const northwind: SweepEvent[] = [
  ev({
    id: "nw-1",
    kind: "phase",
    phase: 1,
    detail: "Four agents take independent briefs. No shared plan.",
  }),
  ev({
    id: "nw-2",
    kind: "status",
    agentId: "dor",
    status: "hunting",
    detail: "HOOK opens on operators, not keywords.",
  }),
  ev({
    id: "nw-3",
    kind: "finding",
    agentId: "dor",
    finding: {
      agentId: "dor",
      subAgent: "FILEHOOK",
      title: "Open index of proforma PDFs",
      body: "An unauthenticated directory at files.nw-logistics.example serves /invoices/2019/ with 41 PDFs. Listing enabled. Filenames follow NW-PRF-####.",
      method: 'intitle:"index of" "nw-logistics" (pdf | invoices) -job -career',
      source: "web index · files.nw-logistics.example/invoices/2019/",
      confidence: 86,
      tags: ["open-directory", "pdf", "invoices"],
    },
  }),
  ev({
    id: "nw-4",
    kind: "message",
    agentId: "dor",
    message: {
      from: "dor",
      to: "all",
      kind: "share",
      body: "HOOK: collection only. 41 PDFs on an open index. I am not reading them. STAMP, these are yours. SPLIT, I have not touched other engines.",
    },
  }),
  ev({
    id: "nw-5",
    kind: "status",
    agentId: "meta",
    status: "analyzing",
    detail: "STAMP starts on producer strings, ignores filenames.",
  }),
  ev({
    id: "nw-6",
    kind: "finding",
    agentId: "meta",
    finding: {
      agentId: "meta",
      subAgent: "STACK",
      title: "Single Acrobat 11.0 producer, author j.harland",
      body: "38/41 PDFs share Producer=Adobe Acrobat 11.0, Author=j.harland, Creator=PScript5.dll. Two outliers: Microsoft Word 2016, author blank. No UK-typical PDF/A. Clock stamps cluster 21:00–01:40.",
      method: "Batch producer/creator/author extraction + hour-of-day histogram",
      source: "document forensics · NW-PRF-2019 set",
      confidence: 81,
      tags: ["pdf-metadata", "author", "acrobat-11"],
    },
  }),
  ev({
    id: "nw-7",
    kind: "status",
    agentId: "scan",
    status: "hunting",
    detail: "SPLIT ignores the PDF index and starts on CT logs.",
  }),
  ev({
    id: "nw-8",
    kind: "finding",
    agentId: "scan",
    finding: {
      agentId: "scan",
      subAgent: "CERT",
      title: "14 certificates, one internal hostname",
      body: "crt.sh-style lattice for nw-logistics.example: 14 leaf certs 2017–2024. SAN includes staging.nw-logistics.internal and vpn-dxb.nw-logistics.example — a Gulf POP the public site never names.",
      method: "Certificate transparency expansion by registrant org + SAN walk",
      source: "CT logs · nw-logistics.example",
      confidence: 84,
      tags: ["ct-logs", "internal-hostname", "san"],
    },
  }),
  ev({
    id: "nw-9",
    kind: "node",
    agentId: "map",
    node: {
      id: "n-nw-org",
      label: "Northwind Logistics Ltd",
      kind: "entity",
      x: 22,
      y: 46,
      note: "UK brass-plate on the public site",
    },
  }),
  ev({
    id: "nw-10",
    kind: "node",
    agentId: "map",
    node: {
      id: "n-nw-pdfs",
      label: "Open invoice index",
      kind: "asset",
      agentId: "dor",
      x: 48,
      y: 22,
    },
  }),
  ev({
    id: "nw-11",
    kind: "node",
    agentId: "map",
    node: {
      id: "n-nw-author",
      label: "j.harland",
      kind: "person",
      agentId: "meta",
      x: 72,
      y: 30,
    },
  }),
  ev({
    id: "nw-12",
    kind: "node",
    agentId: "map",
    node: {
      id: "n-nw-dxb",
      label: "vpn-dxb hostname",
      kind: "asset",
      agentId: "scan",
      x: 58,
      y: 68,
    },
  }),
  ev({
    id: "nw-13",
    kind: "edge",
    agentId: "map",
    edge: { from: "n-nw-org", to: "n-nw-pdfs", rel: "exposes" },
  }),
  ev({
    id: "nw-14",
    kind: "edge",
    agentId: "map",
    edge: { from: "n-nw-pdfs", to: "n-nw-author", rel: "stamped by" },
  }),
  ev({
    id: "nw-15",
    kind: "edge",
    agentId: "map",
    edge: { from: "n-nw-org", to: "n-nw-dxb", rel: "undeclared pop" },
  }),
  ev({
    id: "nw-16",
    kind: "debate",
    agentId: "map",
    debate: {
      a: "dor",
      b: "meta",
      topic: "Where does Northwind actually operate?",
      aPos: "HOOK: the public surface is UK — invoices, Companies-style naming, .co.uk leftovers in paths.",
      bPos: "STAMP: authoring hours and Acrobat 11 sit in a UTC+4 night cluster. The UK story is a cover on the files, not in them.",
    },
  }),
  ev({
    id: "nw-17",
    kind: "finding",
    agentId: "meta",
    finding: {
      agentId: "meta",
      subAgent: "CLOCK",
      title: "UTC+4 night cluster, not BST",
      body: "Modification times on 33/41 files fall 21:12–01:37 with no BST/GMT leap. That is Gulf evening work, not a London back office. Two Word outliers sit at 09:14 UTC — a different hand.",
      method: "Timezone inference from PDF ModDate vs. declared HQ locale",
      source: "document clocks · NW-PRF-2019",
      confidence: 79,
      tags: ["timezone", "utc+4", "clock-skew"],
    },
  }),
  ev({
    id: "nw-18",
    kind: "finding",
    agentId: "scan",
    finding: {
      agentId: "scan",
      subAgent: "WAYBACK",
      title: "2018 careers page names a Dubai entity",
      body: "A 2018-03-12 capture of /careers (dropped from the live index) lists 'Northwind FZE — Jebel Ali' as the hiring entity. Google no longer returns it. Archive is the only lens.",
      method: "Wayback coverage of dropped paths the live index no longer serves",
      source: "web archive · nw-logistics.example/careers",
      confidence: 77,
      tags: ["archive", "fze", "dropped-page"],
    },
  }),
  ev({
    id: "nw-19",
    kind: "message",
    agentId: "scan",
    message: {
      from: "scan",
      to: "map",
      kind: "share",
      body: "SPLIT: HOOK's UK index is real, but it is not the whole surface. Archive and CT both point at a Gulf operating company the live site erased.",
    },
  }),
  ev({
    id: "nw-20",
    kind: "node",
    agentId: "map",
    node: {
      id: "n-nw-fze",
      label: "Northwind FZE (Jebel Ali)",
      kind: "entity",
      agentId: "scan",
      x: 30,
      y: 78,
    },
  }),
  ev({
    id: "nw-21",
    kind: "edge",
    agentId: "map",
    edge: { from: "n-nw-org", to: "n-nw-fze", rel: "fronts" },
  }),
  ev({
    id: "nw-22",
    kind: "edge",
    agentId: "map",
    edge: { from: "n-nw-author", to: "n-nw-fze", rel: "likely desks at" },
  }),
  ev({
    id: "nw-23",
    kind: "finding",
    agentId: "map",
    finding: {
      agentId: "map",
      subAgent: "ONTOLOGY",
      title: "Hypothesis: UK plate, Gulf desk",
      body: "Three independent methods, three different doors, one structure: a UK-facing legal name, a Jebel Ali operating entity, and a document author whose clock never sat in London. Confidence is joint, not any single strand.",
      method: "Cross-method join with contradiction watch (locale vs. clock vs. CT)",
      source: "logic map · Northwind lattice",
      confidence: 74,
      tags: ["hypothesis", "front-company", "join"],
    },
  }),
  ev({
    id: "nw-24",
    kind: "feedback",
    agentId: "map",
    feedback: {
      agentId: "dor",
      delta: 4,
      reason: "Open-directory dork produced the artifact STAMP could actually read.",
    },
  }),
  ev({
    id: "nw-25",
    kind: "feedback",
    agentId: "map",
    feedback: {
      agentId: "meta",
      delta: 6,
      reason: "Clock cluster resolved the debate HOOK could not.",
    },
  }),
  ev({
    id: "nw-26",
    kind: "phase",
    phase: 5,
    detail: "Debrief. Each agent presents a method the others did not use.",
  }),
  ev({
    id: "nw-27",
    kind: "debrief",
    agentId: "dor",
    debrief: {
      agentId: "dor",
      summary:
        "intitle:\"index of\" plus a filename pattern beat every branded-keyword search. I will start on leftover directories before homepages.",
      next: "PATHFINDER will expand /invoices/2019 → adjacent years and /bills/ without repeating STAMP's read.",
    },
  }),
  ev({
    id: "nw-28",
    kind: "debrief",
    agentId: "meta",
    debrief: {
      agentId: "meta",
      summary:
        "Author + hour-of-day outran the UK copy. Acrobat 11 is a dated stack; I will treat producer version as a desk fingerprint, not a footnote.",
      next: "AUTHOR will hunt j.harland as a stamp, never as a search string.",
    },
  }),
  ev({
    id: "nw-29",
    kind: "debrief",
    agentId: "scan",
    debrief: {
      agentId: "scan",
      summary:
        "CT SAN and a dropped careers capture were invisible to HOOK's live index. Coverage is a method, not a fallback.",
      next: "RDAP historical names on the FZE before another live crawl.",
    },
  }),
  ev({
    id: "nw-30",
    kind: "debrief",
    agentId: "map",
    debrief: {
      agentId: "map",
      summary:
        "The useful object was the contradiction, not the consensus. I will keep sending agents back with the gap, not the average.",
      next: "WEIGHT will downrank any claim supported by only one method.",
    },
  }),
];

const helios: SweepEvent[] = [
  ev({
    id: "he-1",
    kind: "phase",
    phase: 4,
    detail: "Exposure cluster. Agents split lenses on purpose.",
  }),
  ev({
    id: "he-2",
    kind: "status",
    agentId: "dor",
    status: "hunting",
    detail: "HOOK hunts leftover buckets and git debris, nothing else.",
  }),
  ev({
    id: "he-3",
    kind: "finding",
    agentId: "dor",
    finding: {
      agentId: "dor",
      subAgent: "PATHFINDER",
      title: "Public listing on backup.helioscloud.example",
      body: "Dork hit: a directory listing of /db-snapshots/ with names snap-2024-11-02.sql.gz (4.1 GB) and snap-2024-11-09.sql.gz. No auth banner. robots.txt disallows it; the index still had it.",
      method: 'inurl:backup "helioscloud" (sql.gz | "index of") -site:statuspage',
      source: "web index · backup.helioscloud.example/db-snapshots/",
      confidence: 88,
      tags: ["backup", "sql", "index-of"],
    },
  }),
  ev({
    id: "he-4",
    kind: "finding",
    agentId: "dor",
    finding: {
      agentId: "dor",
      subAgent: "GHOST",
      title: "Cached .env from a 2023 staging host",
      body: "cache: staging-api.helioscloud.example/.env.example still holds AWS_ACCESS_KEY_ID=AKIA…REDACTED and a Slack webhook path. Live 404s. Ghost page is the only copy.",
      method: "cache: operator on retired staging hosts, never the apex",
      source: "cached page · staging-api.helioscloud.example",
      confidence: 73,
      tags: ["cache", "env", "staging"],
    },
  }),
  ev({
    id: "he-5",
    kind: "status",
    agentId: "meta",
    status: "analyzing",
    detail: "STAMP reads git objects HOOK will not parse.",
  }),
  ev({
    id: "he-6",
    kind: "finding",
    agentId: "meta",
    finding: {
      agentId: "meta",
      subAgent: "AUTHOR",
      title: "Commit stamps leak personal mail",
      body: "A leftover /.git/logs/HEAD (linked from an old status gist, not from HOOK's bucket) shows committer=Maya Chen <maya.chen.home@mailbox.example> on 14 of 22 commits. Corporate mail is never used. Laptop timezone UTC-8.",
      method: "Git committer/author/email/tz extraction from exposed logs",
      source: "git metadata · HeliosCloud historical HEAD",
      confidence: 82,
      tags: ["git", "email", "committer"],
    },
  }),
  ev({
    id: "he-7",
    kind: "status",
    agentId: "scan",
    status: "hunting",
    detail: "SPLIT diffs engines on the staging host, skips the bucket.",
  }),
  ev({
    id: "he-8",
    kind: "finding",
    agentId: "scan",
    finding: {
      agentId: "scan",
      subAgent: "RDAP",
      title: "Staging host only survives on one engine",
      body: "Bing still ranks staging-api.helioscloud.example/health. Google dropped it. Yandex has a 2022 forum paste with the same host and a Grafana path /d/helios-prod. Differential coverage, not a dork.",
      method: "Four-engine diff + forum-index side channel",
      source: "engine delta · staging-api.helioscloud.example",
      confidence: 76,
      tags: ["engine-diff", "bing-only", "grafana"],
    },
  }),
  ev({
    id: "he-9",
    kind: "node",
    agentId: "map",
    node: {
      id: "n-he-org",
      label: "HeliosCloud",
      kind: "entity",
      x: 20,
      y: 50,
    },
  }),
  ev({
    id: "he-10",
    kind: "node",
    agentId: "map",
    node: {
      id: "n-he-snap",
      label: "db-snapshots bucket",
      kind: "asset",
      agentId: "dor",
      x: 48,
      y: 24,
    },
  }),
  ev({
    id: "he-11",
    kind: "node",
    agentId: "map",
    node: {
      id: "n-he-env",
      label: "cached .env",
      kind: "source",
      agentId: "dor",
      x: 46,
      y: 72,
    },
  }),
  ev({
    id: "he-12",
    kind: "node",
    agentId: "map",
    node: {
      id: "n-he-maya",
      label: "Maya Chen (committer)",
      kind: "person",
      agentId: "meta",
      x: 74,
      y: 40,
    },
  }),
  ev({
    id: "he-13",
    kind: "node",
    agentId: "map",
    node: {
      id: "n-he-graf",
      label: "Grafana /d/helios-prod",
      kind: "asset",
      agentId: "scan",
      x: 68,
      y: 74,
    },
  }),
  ev({
    id: "he-14",
    kind: "edge",
    agentId: "map",
    edge: { from: "n-he-org", to: "n-he-snap", rel: "exposes" },
  }),
  ev({
    id: "he-15",
    kind: "edge",
    agentId: "map",
    edge: { from: "n-he-org", to: "n-he-env", rel: "retired secret" },
  }),
  ev({
    id: "he-16",
    kind: "edge",
    agentId: "map",
    edge: { from: "n-he-maya", to: "n-he-org", rel: "commits as" },
  }),
  ev({
    id: "he-17",
    kind: "debate",
    agentId: "map",
    debate: {
      a: "dor",
      b: "scan",
      topic: "Is the backup listing still live, or a ghost?",
      aPos: "HOOK: the index-of response was live when collected. I do not trust archives for this.",
      bPos: "SPLIT: my engine diff says Google already dropped the host. Treat the listing as perishable and capture hashes, do not recrawl.",
    },
  }),
  ev({
    id: "he-18",
    kind: "finding",
    agentId: "map",
    finding: {
      agentId: "map",
      subAgent: "CONTRADICT",
      title: "Exposure is a cluster, not a single hole",
      body: "Bucket, cached env, git mail, and a Bing-only health endpoint are four surfaces with no shared collection method. WEFT will not let one patch close the case.",
      method: "Surface clustering with method-diversity constraint",
      source: "logic map · HeliosCloud cluster",
      confidence: 80,
      tags: ["cluster", "exposure", "diversity"],
    },
  }),
  ev({
    id: "he-19",
    kind: "feedback",
    agentId: "map",
    feedback: {
      agentId: "scan",
      delta: 5,
      reason: "Engine delta prevented a redundant recrawl of a dying listing.",
    },
  }),
  ev({
    id: "he-20",
    kind: "phase",
    phase: 5,
    detail: "Evaluation. Methods stay unshared on purpose.",
  }),
  ev({
    id: "he-21",
    kind: "debrief",
    agentId: "dor",
    debrief: {
      agentId: "dor",
      summary: "robots.txt was a pointer, not a wall. I will dork disallowed paths as a first move on SaaS properties.",
      next: "FILEHOOK on adjacent snapshot naming, no metadata pass.",
    },
  }),
  ev({
    id: "he-22",
    kind: "debrief",
    agentId: "meta",
    debrief: {
      agentId: "meta",
      summary: "Personal mail in git was the identity, not the org domain. I will prefer committer stamps over staff pages.",
      next: "STACK on the AWS key prefix class, without using HOOK's bucket listing.",
    },
  }),
  ev({
    id: "he-23",
    kind: "debrief",
    agentId: "scan",
    debrief: {
      agentId: "scan",
      summary: "One-engine survivors are the interesting set. I will rank Bing/Yandex-only hits above Google consensus.",
      next: "WAYBACK on /d/helios-prod before any live Grafana fetch.",
    },
  }),
  ev({
    id: "he-24",
    kind: "debrief",
    agentId: "map",
    debrief: {
      agentId: "map",
      summary: "I forbade a single-hole narrative. The map is a cluster of independent doors.",
      next: "WEIGHT will require two methods before a surface is marked closed.",
    },
  }),
];

const atlas: SweepEvent[] = [
  ev({
    id: "at-1",
    kind: "phase",
    phase: 4,
    detail: "Public TTP lattice. No live targeting of persons.",
  }),
  ev({
    id: "at-2",
    kind: "status",
    agentId: "dor",
    status: "hunting",
    detail: "HOOK hunts paste syntax and infra strings, not names.",
  }),
  ev({
    id: "at-3",
    kind: "finding",
    agentId: "dor",
    finding: {
      agentId: "dor",
      subAgent: "FILEHOOK",
      title: "Paste names C2 with a distinctive URI",
      body: "A 2025 paste dump indexed as plaintext: 'atlas-7 c2 /gate/v3/u' plus two IPv4s in 185.244.0.0/16. Query was the URI, never the cluster name.",
      method: '"/gate/v3/u" filetype:txt OR site:paste -job',
      source: "indexed paste · public dump",
      confidence: 71,
      tags: ["paste", "c2", "uri"],
    },
  }),
  ev({
    id: "at-4",
    kind: "status",
    agentId: "meta",
    status: "analyzing",
    detail: "STAMP reads a PDF whitepaper HOOK did not fetch as a hunt.",
  }),
  ev({
    id: "at-5",
    kind: "finding",
    agentId: "meta",
    finding: {
      agentId: "meta",
      subAgent: "STACK",
      title: "Whitepaper PDF produced by a design shop",
      body: "A public 'ATLAS-7 technical note' PDF (shared on a vendor blog) has Producer=Adobe InDesign 18.0 (Macintosh), Author=atelier.north, CreationDate 2024-06. Not a researcher toolchain — a comms shop.",
      method: "PDF producer/creator on vendor-published notes, not the paste",
      source: "document forensics · vendor PDF",
      confidence: 69,
      tags: ["pdf", "indesign", "comms-shop"],
    },
  }),
  ev({
    id: "at-6",
    kind: "status",
    agentId: "scan",
    status: "hunting",
    detail: "SPLIT searches non-English indexes HOOK never opened.",
  }),
  ev({
    id: "at-7",
    kind: "finding",
    agentId: "scan",
    finding: {
      agentId: "scan",
      subAgent: "WAYBACK",
      title: "Yandex-only blog names the same URI",
      body: "A 2024 ru-lang blog, invisible on Google/Bing, describes /gate/v3/u as a loader path and lists overlapping netblocks. Unique lens: morphological RU search + archive snapshot.",
      method: "Yandex morphology + archive, excluding Latin-only indexes",
      source: "engine coverage · ru-lang blog",
      confidence: 75,
      tags: ["yandex", "ru", "archive"],
    },
  }),
  ev({
    id: "at-8",
    kind: "node",
    agentId: "map",
    node: {
      id: "n-at-cluster",
      label: "ATLAS-7 cluster",
      kind: "entity",
      x: 24,
      y: 48,
    },
  }),
  ev({
    id: "at-9",
    kind: "node",
    agentId: "map",
    node: {
      id: "n-at-uri",
      label: "/gate/v3/u",
      kind: "asset",
      agentId: "dor",
      x: 52,
      y: 22,
    },
  }),
  ev({
    id: "at-10",
    kind: "node",
    agentId: "map",
    node: {
      id: "n-at-pdf",
      label: "atelier.north PDF",
      kind: "source",
      agentId: "meta",
      x: 78,
      y: 48,
    },
  }),
  ev({
    id: "at-11",
    kind: "node",
    agentId: "map",
    node: {
      id: "n-at-ru",
      label: "RU blog (Yandex)",
      kind: "source",
      agentId: "scan",
      x: 52,
      y: 76,
    },
  }),
  ev({
    id: "at-12",
    kind: "edge",
    agentId: "map",
    edge: { from: "n-at-cluster", to: "n-at-uri", rel: "uses" },
  }),
  ev({
    id: "at-13",
    kind: "edge",
    agentId: "map",
    edge: { from: "n-at-ru", to: "n-at-uri", rel: "corroborates" },
  }),
  ev({
    id: "at-14",
    kind: "edge",
    agentId: "map",
    edge: { from: "n-at-pdf", to: "n-at-cluster", rel: "narrates" },
  }),
  ev({
    id: "at-15",
    kind: "debate",
    agentId: "map",
    debate: {
      a: "meta",
      b: "scan",
      topic: "Is the vendor PDF reporting, or laundering a narrative?",
      aPos: "STAMP: InDesign + a shop author is comms, not analysis. Treat the note as influence, not evidence.",
      bPos: "SPLIT: the RU blog predates the PDF and independently names the URI. The PDF can be marketing and the URI still real.",
    },
  }),
  ev({
    id: "at-16",
    kind: "finding",
    agentId: "map",
    finding: {
      agentId: "map",
      subAgent: "WEIGHT",
      title: "URI is the join; the PDF is not",
      body: "Paste (HOOK) and RU blog (SPLIT) independently hold /gate/v3/u. The InDesign note is a later narrative layer and is downweighted as evidence, kept as an influence node.",
      method: "Independent-corroboration rule; narrative sources demoted",
      source: "logic map · ATLAS-7",
      confidence: 72,
      tags: ["ttp", "join", "weighting"],
    },
  }),
  ev({
    id: "at-17",
    kind: "feedback",
    agentId: "map",
    feedback: {
      agentId: "meta",
      delta: 3,
      reason: "Producer string stopped the PDF from being treated as primary evidence.",
    },
  }),
  ev({
    id: "at-18",
    kind: "feedback",
    agentId: "map",
    feedback: {
      agentId: "scan",
      delta: 7,
      reason: "Non-English engine was the only independent corroboration.",
    },
  }),
  ev({
    id: "at-19",
    kind: "phase",
    phase: 5,
    detail: "Debrief on public TTPs only.",
  }),
  ev({
    id: "at-20",
    kind: "debrief",
    agentId: "dor",
    debrief: {
      agentId: "dor",
      summary: "URI-first dorks beat cluster-name searches, which are polluted by the vendor note.",
      next: "GHOST on historical pastes with the same path, no PDF.",
    },
  }),
  ev({
    id: "at-21",
    kind: "debrief",
    agentId: "meta",
    debrief: {
      agentId: "meta",
      summary: "Design-shop producer strings are a tell for narrative products. I will flag InDesign/Quark on 'intel notes'.",
      next: "CLOCK on the PDF vs. the RU blog timestamps.",
    },
  }),
  ev({
    id: "at-22",
    kind: "debrief",
    agentId: "scan",
    debrief: {
      agentId: "scan",
      summary: "Latin indexes were a monoculture. Coverage means changing the language of the lens.",
      next: "CERT on the 185.244 netblock, not on the cluster name.",
    },
  }),
  ev({
    id: "at-23",
    kind: "debrief",
    agentId: "map",
    debrief: {
      agentId: "map",
      summary: "I separated infrastructure evidence from storytelling. The map now has two layers: TTP and narrative.",
      next: "ONTOLOGY will keep influence nodes visually apart from assets.",
    },
  }),
];

function pack(
  id: string,
  code: string,
  title: string,
  target: string,
  synopsis: string,
  script: SweepEvent[],
  startedAt: number,
  status: Investigation["status"],
  phase: number,
): Investigation {
  return {
    id,
    code,
    title,
    target,
    synopsis,
    status,
    phase,
    startedAt,
    cursor: 0,
    script,
    findings: [],
    messages: [],
    nodes: [],
    edges: [],
    runtime: freshRuntime(),
    synthetic: true,
  };
}

const T0 = Date.UTC(2026, 8, 18, 14, 20, 0);

export function seedCases(): Investigation[] {
  const a = pack(
    "case-northwind",
    "NW-19",
    "Northwind Logistics",
    "Northwind Logistics Ltd",
    "UK-facing freight plate. Four agents, four doors: open invoices, PDF clocks, CT hostnames, a dropped careers page.",
    northwind,
    T0,
    "active",
    1,
  );
  const b = pack(
    "case-helios",
    "HC-04",
    "HeliosCloud cluster",
    "HeliosCloud",
    "Exposure cluster on a fictional SaaS: leftover snapshots, a cached env, git stamps, a Bing-only health host.",
    helios,
    T0 - 86400000 * 2,
    "paused",
    4,
  );
  const c = pack(
    "case-atlas",
    "AT-7",
    "ATLAS-7 public TTPs",
    "ATLAS-7 cluster",
    "Public infrastructure lattice only. Paste URI, a comms-shop PDF, a Yandex-only corroboration.",
    atlas,
    T0 - 86400000 * 6,
    "debrief",
    5,
  );
  return [a, b, c];
}

export const PRELOAD = {
  northwind: 16,
  helios: 18,
  atlas: 999,
} as const;
