/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FrameworkRouteImport } from './routes/framework'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as MeshRouteImport } from './routes/mesh'
import { Route as CaseCaseIdRouteImport } from './routes/case.$caseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FrameworkRoute = FrameworkRouteImport.update({
  id: '/framework',
  path: '/framework',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const MeshRoute = MeshRouteImport.update({
  id: '/mesh',
  path: '/mesh',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseCaseIdRoute = CaseCaseIdRouteImport.update({
  id: '/case/$caseId',
  path: '/case/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/dashboard': typeof DashboardRoute
  '/framework': typeof FrameworkRoute
  '/learn': typeof LearnRoute
  '/mesh': typeof MeshRoute
  '/case/$caseId': typeof CaseCaseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/dashboard': typeof DashboardRoute
  '/framework': typeof FrameworkRoute
  '/learn': typeof LearnRoute
  '/mesh': typeof MeshRoute
  '/case/$caseId': typeof CaseCaseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/dashboard': typeof DashboardRoute
  '/framework': typeof FrameworkRoute
  '/learn': typeof LearnRoute
  '/mesh': typeof MeshRoute
  '/case/$caseId': typeof CaseCaseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/dashboard'
    | '/framework'
    | '/learn'
    | '/mesh'
    | '/case/$caseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/dashboard'
    | '/framework'
    | '/learn'
    | '/mesh'
    | '/case/$caseId'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/dashboard'
    | '/framework'
    | '/learn'
    | '/mesh'
    | '/case/$caseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  DashboardRoute: typeof DashboardRoute
  FrameworkRoute: typeof FrameworkRoute
  LearnRoute: typeof LearnRoute
  MeshRoute: typeof MeshRoute
  CaseCaseIdRoute: typeof CaseCaseIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/framework': {
      id: '/framework'
      path: '/framework'
      fullPath: '/framework'
      preLoaderRoute: typeof FrameworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mesh': {
      id: '/mesh'
      path: '/mesh'
      fullPath: '/mesh'
      preLoaderRoute: typeof MeshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case/$caseId': {
      id: '/case/$caseId'
      path: '/case/$caseId'
      fullPath: '/case/$caseId'
      preLoaderRoute: typeof CaseCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  DashboardRoute: DashboardRoute,
  FrameworkRoute: FrameworkRoute,
  LearnRoute: LearnRoute,
  MeshRoute: MeshRoute,
  CaseCaseIdRoute: CaseCaseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
